### ISSUE TITLE
Ethgasstationapi CORS Issue

### ISSUE THREAD

**Issue by WizardsOrb** [saturn-network/saturn.js#7]
https://github.com/saturn-network/saturn.js/blob/2918c17c2a8be86cf6bccfbb459605fc8ce2cad5/src/exchange/exchange.ts#L330-L333

Finally i did find some time for coding again, and i started to use SaturnJs on Ethereum. I am facing a CORS issue on Brave and Chrome/ium - Firefox seems to work fine. Its only solvable through a [CORS plugin](https://mybrowseraddon.com/access-control-allow-origin.html). For "normal" users this could be annoying.

![CORSERRORSCREEN](https://user-images.githubusercontent.com/45433868/72759441-0ae45e00-3bd6-11ea-85d8-d81fdf00bef7.png)

As a quick and simple solution we can put this function into a `try / catch block`and return for example 5 Gwei gasprice by default. This can also be useful in case the the gasstation api is down.

> Note, this bug is only on Browser, on nodejs / ts-node i dont see this issue.

```ts
if (this.blockchain.toUpperCase() === "ETH") { 
  try{
    let gasApiUrl = 'https://www.ethgasstationapi.com/api/standard' 
    return (await axios.get(gasApiUrl)).data * 1000000000 
  }catch(e){
    console.error("CORS ERROR GASSTATION")
    return 5000000000 // 5 gwei
  }
 } 
```

if you have a better solution on this issue, please let me know.

future is bright.

**Comment by saturn-network** [comment]
Thanks for reporting this! Fixed in v0.1.7
